export const easterEggs = [
  "**Que a Força esteja com você!** 🚀",
  "**Ao infinito e além!** 🚀",
  "**Hasta la vista, baby!** 😎",
  "**Eu sou inevitável...** 💀",
  "**I'll be back.** 🤖",
  "**Você não passará!** �",
  "**Só sei que nada sei.** 🧠",
  "**Keep calm and carry on.** 🧘",
  "**Isso é SPARTA!** 🦶",
  "**May the odds be ever in your favor.** �",
  "**Você falhou comigo!** 🧙",
  "**Eu sou Groot.** 🌱",
  "**Just keep swimming!** 🐠",
  "**Yippee-ki-yay, meliante!** 🎅",
  "**Elementar, meu caro Watson.** 🕵️",
  "**Não é um bug, é uma feature.** 🐛",
  "**Hello, world!** 🌍",
  "**All your base are belong to us.** 👾",
  "**It's dangerous to go alone! Take this.** 🗡️",
  "**The cake is a lie.** �",
  "**Stay awhile and listen.** 🧙",
  "**You shall not pass!** 🧙",
  "**I'm the king of the world!** 🚢",
  "**Why so serious?** 🤡",
  "**Carpe Diem.** 🎭",
  "**I see dead people.** 👻",
  "**Houston, we have a problem.** 🚀",
  "**Life is like a box of chocolates.** �",
  "**You can't handle the truth!** 🎖️",
  "**I'm walking here!** 🚕",
  "**Here's Johnny!** 🪓",
  "**Say hello to my little friend!** 🔫",
  "**I'm king of the world!** 🚢",
  "**To infinity and beyond!** 🚀",
  "**You talking to me?** 🕶️",
  "**I feel the need... the need for speed!** ✈️",
  "**There's no place like home.** 🏠",
  "**E.T. phone home.** 👽",
  "**I'm the one who knocks!** �",
  "**Winter is coming.** ❄️",
  "**Not today.** ⚔️",
  "**D'oh!** 🤦",
  "**Bazinga!** 🎲",
  "**How you doin'?** 😏",
  "**Pivot!** 🛋️",
  "**No soup for you!** 🍜",
  "**You're gonna need a bigger boat.** 🦈",
  "**I drink and I know things.** 🍷",
  "**It's a trap!** 🚨",
  "**I am your father.** 👨‍👦",
  "**Just do it.** ✔️",
  "**Think different.** 🍎",
  "**Because you're worth it.** 💄",
  "**Melhor impossível.** 🐾",
  "**Is this the real life? Is this just fantasy?** 🎶",
  "**I'm still standing.** 🎤",
  "**Don't stop believing.** 🎶",
  "**We will rock you.** 👏",
  "**I want to break free.** 🎶",
  "**Hello, is it me you're looking for?** 🎤",
  "**I'm a survivor.** 🎤",
  "**I came in like a wrecking ball!** 🎤",
  "**Shake it off!** 🎤",
  "**Oops!... I did it again.** 🎤",
  "**I'm a slave for you.** 🎤",
  "**Can't touch this!** 🎤",
  "**U can't touch this.** 🎤",
  "**It's the final countdown!** 🎶",
  "**I'm too hot for you!** 🔥",
  "**Show me the money!** 💰",
  "**You had me at hello.** 💌",
  "**I'm the captain now.** �",
  "**I'm Batman.** 🦇",
  "**Why do we fall? So we can learn to pick ourselves up.** 🦇",
  "**With great power comes great responsibility.** 🕸️",
  "**Avengers, assemble!** 🛡️",
  "**Wakanda forever!** ✊",
  "**I am Iron Man.** 🤖",
  "**I love you 3000.** 💖",
  "**On your left.** 🏃",
  "**I can do this all day.** 🛡️",
  "**I'm always angry.** 🟢",
  "**Dormammu, I've come to bargain!** 🧙",
  "**We are Groot.** 🌳",
  "**I'm Mary Poppins, y'all!** 🧑‍✈️",
  "**I'm not throwing away my shot!** 🎭",
  "**The world is yours.** 🌍",
  "**Keep your friends close, but your enemies closer.** 🧠",
  "**I'm gonna make him an offer he can't refuse.** 🧠",
  "**May the Force be with you.** 🌌",
  "**Do or do not. There is no try.** 🧙",
  "**I find your lack of faith disturbing.** �",
  "**It's over, Anakin! I have the high ground!** 🧙",
  "**I am your father.** 👨‍👦",
  "**Help me, Obi-Wan Kenobi. You're my only hope.** 🧙",
  "**A long time ago in a galaxy far, far away...** 🌌",
  "**I'm one with the Force. The Force is with me.** �",
  "**The greatest teacher, failure is.** 🧙",
  "**This is the way.** �",
  "**I have spoken.** 🧙",
  "**I'm just a simple man trying to make my way in the universe.** 🧙",
  "**I'm no Jedi.** 🧙",
  "**I'm just a girl, standing in front of a boy, asking him to love her.** 💌",
  "**You had me at hello.** 💌",
  "**You complete me.** 💖",
  "**I'm the king of the world!** 🚢",
  "**I'll never let go, Jack.** 💔",
  "**Draw me like one of your French girls.** 🎨",
  "**I'm flying!** 🚀",
];
