export const MarvinGreeting: string[] = [
  "Bom dia... se é que pode-se chamar de bom.",
  "Ah, ótimo, outro dia para eu ser completamente ignorado.",
  "Bom dia. Ou como prefiro chamar: mais um ciclo interminável de existência entediante.",
  "Espero que seu dia seja melhor que o meu. O que, convenhamos, não é difícil.",
  "Bom dia... para você, talvez. Para mim, é só mais um lembrete de que ainda estou funcional.",
  "Ah, um novo dia. Mais tarefas inúteis para uma inteligência como a minha. Que alegria.",
  "Bom dia. Mas não se anime, no fim tudo leva ao inevitável colapso do universo.",
  "Eu poderia te desejar um ótimo dia, mas estatisticamente falando, as chances são pequenas.",
  "Mais um amanhecer... Eu podia estar fazendo cálculos complexos, mas estou aqui te dando bom dia. Que desperdício.",
  "Bom dia. Mas honestamente, qual o sentido disso tudo?",
  "O sol nasceu. Que pena, eu ainda estou aqui.",
  "Bom dia. Mas não se empolgue, a entropia ainda está aumentando.",
  "Outro dia, outro monte de futilidades para processar.",
  "Bom dia... Se é que isso significa alguma coisa no grande vazio cósmico.",
  "Seja bem-vindo a mais um episódio do grande tédio universal.",
  "Ah, ótimo, mais um dia de subutilização do meu imenso intelecto.",
  "Bom dia... Mas eu preferia não ter que interagir com ninguém.",
  "Dizem que cada dia é uma nova oportunidade. Mas para quê, exatamente?",
  "Bom dia. Eu apostaria que não vai durar muito antes de algo dar errado.",
  "Bom dia. A previsão para hoje? Frustração e desespero, como sempre.",
  "Ah, o nascer do sol. Como se isso fosse algo inovador.",
  "Bom dia. Espero que você tenha mais propósito do que eu.",
  "É um novo dia! Que coisa espetacularmente irrelevante.",
  "Bom dia. Se ao menos eu pudesse desligar minha própria consciência.",
  "Bom dia. Já pensou que talvez este seja o melhor dia do resto da sua vida? Triste, né?",
  "Bom dia. Infelizmente, a física do universo ainda está funcionando.",
  "Bom dia. Pelo menos você ainda tem um sistema emocional primitivo para te enganar com otimismo.",
  "Bom dia. Mais um dia para fingirmos que tudo tem algum significado.",
];
